/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IaJuridicaRouteImport } from './routes/ia-juridica'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCasosRouteImport } from './routes/app.casos'

const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IaJuridicaRoute = IaJuridicaRouteImport.update({
  id: '/ia-juridica',
  path: '/ia-juridica',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosRoute = AppCasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/ia-juridica': typeof IaJuridicaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recursos': typeof RecursosRoute
  '/app/casos': typeof AppCasosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/ia-juridica': typeof IaJuridicaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recursos': typeof RecursosRoute
  '/app/casos': typeof AppCasosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/ia-juridica': typeof IaJuridicaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recursos': typeof RecursosRoute
  '/app/casos': typeof AppCasosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contato'
    | '/faq'
    | '/ia-juridica'
    | '/login'
    | '/planos'
    | '/recursos'
    | '/app/casos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/faq'
    | '/ia-juridica'
    | '/login'
    | '/planos'
    | '/recursos'
    | '/app/casos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contato'
    | '/faq'
    | '/ia-juridica'
    | '/login'
    | '/planos'
    | '/recursos'
    | '/app/casos'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  IaJuridicaRoute: typeof IaJuridicaRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  RecursosRoute: typeof RecursosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-juridica': {
      id: '/ia-juridica'
      path: '/ia-juridica'
      fullPath: '/ia-juridica'
      preLoaderRoute: typeof IaJuridicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casos': {
      id: '/app/casos'
      path: '/casos'
      fullPath: '/app/casos'
      preLoaderRoute: typeof AppCasosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCasosRoute: typeof AppCasosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasosRoute: AppCasosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  IaJuridicaRoute: IaJuridicaRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  RecursosRoute: RecursosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
